import os
from PIL import Image
from models.nano_arcked_02.inference.nanopixel_engine import NanoArcKed02Engine

def main():
    showcase_dir = "examples/nano_arcked_02_showcase"
    os.makedirs(showcase_dir, exist_ok=True)

    engine = NanoArcKed02Engine(device="cpu")

    characters = [
        ("char_01_paladin_knight", "pixel paladin knight in gold armor", "signature"),
        ("char_02_fire_mage", "pixel fire mage wizard with staff", "nes"),
        ("char_03_cyber_ninja", "pixel cyber ninja warrior", "gameboy"),
        ("char_04_mecha_mech", "pixel mecha robot suit", "signature"),
        ("char_05_retro_orc", "pixel retro orc monster warrior", "nes")
    ]

    print(f"Generating NanoArcKed-02 Showcase Assets in {showcase_dir}...")

    for char_id, prompt, palette_mode in characters:
        sprite = engine.generate_sprite(prompt, palette_mode=palette_mode, seed=42)
        sprite_path = os.path.join(showcase_dir, f"{char_id}_single.png")
        sprite.save(sprite_path)

        frames, sheet, gif_bytes = engine.generate_animation(sprite, action="run", num_frames=4, palette_mode=palette_mode)
        sheet_path = os.path.join(showcase_dir, f"{char_id}_spritesheet.png")
        sheet.save(sheet_path)

        gif_path = os.path.join(showcase_dir, f"{char_id}_animation.gif")
        with open(gif_path, "wb") as gf:
            gf.write(gif_bytes)

        print(f"  [Showcase] Generated assets for {char_id} ({palette_mode} palette).")

    readme_path = os.path.join(showcase_dir, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write("# NanoArcKed-02 Showcase Outputs\n\n")
        f.write("This folder contains 64x64 pixel art character outputs generated by `NanoArcKed-02`.\n\n")
        f.write("## Features Included:\n")
        f.write("- **Text-to-Image (T2I)** generation\n")
        f.write("- **Image-to-Image (I2I)** character refinement\n")
        f.write("- **Animated GIF** and **Sprite Sheet** generation\n")
        f.write("- **Game Boy** (4-color green) & **NES** (16-color retro) palette quantization\n")

    print("\nNanoArcKed-02 Showcase Generation Complete!")

if __name__ == "__main__":
    main()
